@startuml

skinparam defaultFontName Courier

Class Building {
    INTEGER      ★ id          
    BOOLEAN      ⚪ availability
    VARCHAR[40]  ⚪ code        
    VARCHAR[150] ⚪ description 
}

Class Floor {
    INTEGER      ★ id          
    INTEGER      ☆ building_id 
    BOOLEAN      ⚪ availability
    VARCHAR[250] ⚪ code        
    VARCHAR[150] ⚪ description 
    +            building      
}

Class Location {
    INTEGER      ★ id              
    INTEGER      ☆ floor_id        
    BOOLEAN      ⚪ aircondition    
    BOOLEAN      ⚪ availability    
    BOOLEAN      ⚪ board           
    VARCHAR[250] ⚪ code            
    INTEGER      ⚪ color           
    BOOLEAN      ⚪ datashow        
    VARCHAR[150] ⚪ description     
    INTEGER      ⚪ exam_capacity   
    INTEGER      ⚪ regular_capacity
    +            compnents         
    +            floor             
    +            roles             
    +            subjects          
}

Class Component {
    INTEGER      ★ id     
    VARCHAR[150] ⚪ name   
    +            locations
}

Class component_location {
    INTEGER ☆ component_id
    INTEGER ☆ location_id 
}

Class Department {
    INTEGER      ★ id         
    INTEGER      ☆ building_id
    VARCHAR[250] ⚪ code       
    VARCHAR[150] ⚪ name       
    +            building     
}

Class Staff {
    INTEGER      ★ id           
    INTEGER      ☆ department_id
    VARCHAR[100] ⚪ name         
    VARCHAR[10]  ⚪ position     
    +            department     
}

Class Subject {
    INTEGER     ★ id           
    INTEGER     ☆ department_id
    VARCHAR[50] ⚪ code         
    INTEGER     ⚪ lecture_time 
    VARCHAR[50] ⚪ name         
    +           department     
    +           location       
}

Class location_subject {
    INTEGER ☆ location_id
    INTEGER ☆ subject_id 
}

Class User {
    INTEGER      ★ id       
    INTEGER      ☆ role_id  
    VARCHAR[100] ⚪ email    
    VARCHAR[150] ⚪ full_name
    VARCHAR[50]  ⚪ name     
    VARCHAR[30]  ⚪ password 
}

Class Role {
    INTEGER      ★ id         
    VARCHAR[200] ⚪ Description
    VARCHAR[50]  ⚪ name       
    +            locations    
}

Class role_locations {
    INTEGER ☆ location_id
    INTEGER ☆ role_id    
}

Floor <--o Building: building_id

Location <--o Floor: floor_id

component_location <--o Component: component_id

component_location <--o Location: location_id

Department <--o Building: building_id

Staff <--o Department: department_id

Subject <--o Department: department_id

location_subject <--o Subject: subject_id

location_subject <--o Location: location_id

User <--o Role: role_id

role_locations <--o Role: role_id

role_locations <--o Location: location_id

right footer generated by sadisplay v0.4.9

@enduml